Layout/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 50

Metrics/BlockLength:
  Max: 50

Style/Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength: 
  Enabled: false

Metrics/AbcSize: 
  Enabled: false

Metrics/CyclomaticComplexity: 
  Enabled: false

Style/AsciiComments: 
  Enabled: false
